apiVersion: v1
kind: Pod
metadata:
  name: ml-in-prod
  labels:
    app: ml-in-prod
spec:
  containers:
    - image: fahrengeit/online_inference:v2
      name: ml-in-prod
      ports:
        - containerPort: 8000
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
        initialDelaySeconds: 10
        periodSeconds: 3
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
          httpHeaders:
            - name: Custom-Header
              value: Awesome
        initialDelaySeconds: 27
        periodSeconds: 5