apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-in-prod
  labels:
    app: ml-in-prod
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: ml-in-prod
  template:
    metadata:
      name: ml-in-prod
      labels:
        app: ml-in-prod
    spec:
      containers:
        - image: fahrengeit/online_inference:v1
          name: ml-in-prod
          ports:
            - containerPort: 8000