apiVersion: v1
kind: Pod
metadata:
  name: ml-in-prod
  labels:
    app: ml-in-prod
spec:
  containers:
    - image: fahrengeit/online_inference:v1
      name: ml-in-prod
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "1Gi"
          cpu: "200m"
        limits:
          memory: "2Gi"
          cpu: "500m"